# Generated by Django 5.1.6 on 2025-03-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="master_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unique_no", models.CharField(max_length=50)),
                ("scheme_code", models.CharField(max_length=50)),
                ("rta_scheme_code", models.CharField(max_length=50)),
                ("amc_scheme_code", models.CharField(max_length=50)),
                ("isin", models.CharField(max_length=50)),
                ("amc_code", models.CharField(max_length=50)),
                ("scheme_type", models.CharField(max_length=50)),
                ("scheme_plan", models.CharField(max_length=50)),
                ("scheme_name", models.CharField(max_length=50)),
                ("purchase_allowed", models.CharField(max_length=50)),
                ("purchase_transaction_mode", models.CharField(max_length=50)),
                ("minimum_purchase_amount", models.CharField(max_length=50)),
                ("additional_purchase_amount", models.CharField(max_length=50)),
                ("maximum_purchase_amount", models.CharField(max_length=50)),
                ("purchase_amount_multiplier", models.CharField(max_length=50)),
                ("purchase_cutoff_time", models.CharField(max_length=50)),
                ("redemption_allowed", models.CharField(max_length=50)),
                ("redemption_transaction_mode", models.CharField(max_length=50)),
                ("minimum_redemption_qty", models.CharField(max_length=50)),
                ("redemption_qty_multiplier", models.CharField(max_length=50)),
                ("maximum_redemption_qty", models.CharField(max_length=50)),
                ("redemption_amount_minimum", models.CharField(max_length=50)),
                ("redemption_amount_maximum", models.CharField(max_length=50)),
                ("redemption_amount_multiple", models.CharField(max_length=50)),
                ("redemption_cut_off_time", models.CharField(max_length=50)),
                ("rta_agent_code", models.CharField(max_length=50)),
                ("amc_active_flag", models.CharField(max_length=50)),
                ("dividend_reinvestment_flag", models.CharField(max_length=50)),
                ("sip_flag", models.CharField(max_length=50)),
                ("stp_flag", models.CharField(max_length=50)),
                ("swp_flag", models.CharField(max_length=50)),
                ("switch_flag", models.CharField(max_length=50)),
                ("settlement_type", models.CharField(max_length=50)),
                ("amc_ind", models.CharField(max_length=50)),
                ("face_value", models.CharField(max_length=50)),
                ("start_date", models.CharField(max_length=50)),
                ("end_date", models.CharField(max_length=50)),
                ("exit_load_flag", models.CharField(max_length=50)),
                ("exit_load", models.CharField(max_length=50)),
                ("lock_in_period_flag", models.CharField(max_length=50)),
                ("lock_in_period", models.CharField(max_length=50)),
                ("channel_partner_code", models.CharField(max_length=50)),
                ("reopening_date", models.CharField(max_length=50)),
            ],
        ),
    ]
