# Generated by Django 5.1.6 on 2025-03-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "datacollection",
            "0003_alter_master_data_additional_purchase_amount_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Nav_datas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isin", models.CharField(max_length=50)),
                ("aum_in_cr", models.CharField(max_length=50)),
                ("net_expense_ratio", models.CharField(max_length=50)),
                ("nav", models.CharField(max_length=50)),
                ("day_change_in_per", models.CharField(max_length=50)),
                ("week_change_in_per", models.CharField(max_length=50)),
                ("month_change_in_per", models.CharField(max_length=50)),
                ("ret_in_three_months_per", models.CharField(max_length=50)),
                ("ret_in_one_year_per", models.CharField(max_length=50)),
                ("two_year_cagr", models.CharField(max_length=50)),
                ("three_year_cagr", models.CharField(max_length=50)),
                ("five_year_cagr", models.CharField(max_length=50)),
                ("plan", models.CharField(max_length=50)),
                ("category", models.CharField(max_length=50)),
            ],
        ),
    ]
