# Generated by Django 5.1.6 on 2025-03-20 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datacollection", "0004_nav_datas"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nav_datas",
            name="id",
        ),
        migrations.AddField(
            model_name="nav_datas",
            name="temp_unique_number",
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
