# Generated by Django 5.1.7 on 2025-03-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0005_remove_nav_datas_id_nav_datas_temp_unique_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nav_datas',
            name='day_change_in_per',
        ),
        migrations.RemoveField(
            model_name='nav_datas',
            name='month_change_in_per',
        ),
        migrations.RemoveField(
            model_name='nav_datas',
            name='nav',
        ),
        migrations.RemoveField(
            model_name='nav_datas',
            name='ret_in_one_year_per',
        ),
        migrations.RemoveField(
            model_name='nav_datas',
            name='ret_in_three_months_per',
        ),
        migrations.RemoveField(
            model_name='nav_datas',
            name='two_year_cagr',
        ),
        migrations.RemoveField(
            model_name='nav_datas',
            name='week_change_in_per',
        ),
        migrations.AddField(
            model_name='nav_datas',
            name='src_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
