# Generated by Django 5.1.7 on 2025-03-23 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0006_remove_nav_datas_day_change_in_per_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nav_datas',
            new_name='Aum_datas',
        ),
    ]
