# Generated by Django 5.1.7 on 2025-03-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0007_rename_nav_datas_aum_datas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nav_Datas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_code', models.CharField(max_length=50)),
                ('isin', models.CharField(max_length=50)),
                ('isin_div_reinversment', models.CharField(max_length=50)),
                ('scheme_name', models.CharField(max_length=200)),
                ('nav', models.CharField(max_length=50)),
                ('dates', models.CharField(max_length=20)),
            ],
        ),
    ]
