# Generated by Django 5.1.7 on 2025-03-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0008_nav_datas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nav_datas',
            name='id',
        ),
        migrations.AddField(
            model_name='nav_datas',
            name='temp_unique_number',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
