# Generated by Django 5.1.7 on 2025-03-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0009_remove_nav_datas_id_nav_datas_temp_unique_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nav_datas',
            name='isin',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='nav_datas',
            name='isin_div_reinversment',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='nav_datas',
            name='nav',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='nav_datas',
            name='scheme_code',
            field=models.CharField(max_length=100),
        ),
    ]
